/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package config;

import config.Application;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class ApplicationTest
{
	@Test
	void appHasAGreeting()
	{
		final Application classUnderTest = new Application();
		assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
	}
}
