/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package config;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class Application
{
	private static final Logger logger = LogManager.getLogger(Application.class);

	public String getGreeting()
	{
		return "Hello world.";
	}

	public static void main(String[] args)
	{
		logger.info(new Application().getGreeting());
	}
}
